project_id = "uvctuukpfzobzawjcgqh"

[functions.get-shared-proposal]
verify_jwt = false

[functions.chat-assistant]
verify_jwt = false

[functions.generate-proposal-content]
verify_jwt = false

[functions.dodo-checkout]
verify_jwt = false

[functions.dodo-webhook]
verify_jwt = false
