// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jiaonmmwvgbhzetkkrnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppYW9ubW13dmdiaHpldGtrcm56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NDAyMjcsImV4cCI6MjA3MTUxNjIyN30.yWW4blaCPancPyEgc-0JE_GqoEF7g1Sic3Qkgr5zpQY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});