// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmgmjfifunncweqgnbvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttZ21qZmlmdW5uY3dlcWduYnZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0ODA1MDUsImV4cCI6MjA3NDA1NjUwNX0.JbRhR5m490SkQZrp0wX2grh7KGSgrOwRMKJX_4xE2Ew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});